/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoCalculadora;

/**
 *
 * @author bruno
 */
public class CalculadoraForm extends javax.swing.JFrame {
    
    
    int virgula = 0;
    int operacao =0;
    double num1, num2;
    
     Calculadora calc = new Calculadora();
    public CalculadoraForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButtonMais = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jButtonMultiplicacao = new javax.swing.JButton();
        jButtonDivisao = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonInverso = new javax.swing.JButton();
        jButtonRaiz = new javax.swing.JButton();
        jTextFieldConta = new javax.swing.JTextField();
        jButtonVirgula = new javax.swing.JButton();
        jTextFieldCalculo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonPorcentagem = new javax.swing.JButton();

        jButton10.setText("jButton10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Russell Calc");
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        setForeground(new java.awt.Color(204, 255, 153));
        setSize(new java.awt.Dimension(400, 700));

        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("3");
        jButton3.setIconTextGap(8);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("1");
        jButton1.setIconTextGap(8);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("2");
        jButton2.setIconTextGap(8);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setForeground(new java.awt.Color(0, 0, 204));
        jButton4.setText("4");
        jButton4.setIconTextGap(8);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setForeground(new java.awt.Color(0, 0, 204));
        jButton5.setText("5");
        jButton5.setIconTextGap(8);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setForeground(new java.awt.Color(0, 0, 204));
        jButton6.setText("6");
        jButton6.setIconTextGap(8);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setForeground(new java.awt.Color(0, 0, 204));
        jButton7.setText("7");
        jButton7.setIconTextGap(8);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setForeground(new java.awt.Color(0, 0, 204));
        jButton8.setText("8");
        jButton8.setIconTextGap(8);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setForeground(new java.awt.Color(0, 0, 204));
        jButton9.setText("9");
        jButton9.setIconTextGap(8);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton0.setForeground(new java.awt.Color(0, 0, 204));
        jButton0.setText("0");
        jButton0.setIconTextGap(8);
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButtonIgual.setForeground(new java.awt.Color(0, 0, 204));
        jButtonIgual.setText("=");
        jButtonIgual.setIconTextGap(8);
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        jButtonMais.setForeground(new java.awt.Color(0, 0, 204));
        jButtonMais.setText("+");
        jButtonMais.setIconTextGap(8);
        jButtonMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaisActionPerformed(evt);
            }
        });

        jButtonMenos.setForeground(new java.awt.Color(0, 0, 204));
        jButtonMenos.setText("-");
        jButtonMenos.setIconTextGap(8);
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        jButtonMultiplicacao.setForeground(new java.awt.Color(0, 0, 204));
        jButtonMultiplicacao.setText("x");
        jButtonMultiplicacao.setIconTextGap(8);
        jButtonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacaoActionPerformed(evt);
            }
        });

        jButtonDivisao.setForeground(new java.awt.Color(0, 0, 204));
        jButtonDivisao.setText("/");
        jButtonDivisao.setIconTextGap(8);
        jButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisaoActionPerformed(evt);
            }
        });

        jButtonC.setForeground(new java.awt.Color(0, 0, 204));
        jButtonC.setText("C");
        jButtonC.setIconTextGap(8);
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonInverso.setForeground(new java.awt.Color(0, 0, 204));
        jButtonInverso.setText("1/x");
        jButtonInverso.setIconTextGap(8);
        jButtonInverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInversoActionPerformed(evt);
            }
        });

        jButtonRaiz.setForeground(new java.awt.Color(0, 0, 204));
        jButtonRaiz.setText("RAIZ");
        jButtonRaiz.setIconTextGap(8);
        jButtonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaizActionPerformed(evt);
            }
        });

        jTextFieldConta.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextFieldConta.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldConta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldConta.setText("0");
        jTextFieldConta.setEnabled(false);
        jTextFieldConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContaActionPerformed(evt);
            }
        });

        jButtonVirgula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonVirgula.setForeground(new java.awt.Color(0, 0, 204));
        jButtonVirgula.setText(",");
        jButtonVirgula.setIconTextGap(8);
        jButtonVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVirgulaActionPerformed(evt);
            }
        });

        jTextFieldCalculo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCalculo.setEnabled(false);
        jTextFieldCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCalculoActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Calculadora Desenvolvida por  Bruno França");

        jButtonPorcentagem.setForeground(new java.awt.Color(0, 0, 204));
        jButtonPorcentagem.setText("%");
        jButtonPorcentagem.setIconTextGap(8);
        jButtonPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPorcentagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jTextFieldConta, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jButtonRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButtonPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)
                            .addComponent(jButtonInverso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButtonDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButtonMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jButtonVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jButtonMais, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jTextFieldCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jTextFieldConta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonInverso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMais, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             if ( jTextFieldConta.getText().equals("0")){
                   jTextFieldConta.setText("3");
              }
             else{     
            jTextFieldConta.setText(jTextFieldConta.getText()+"3");
              }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             if ( jTextFieldConta.getText().equals("0")){
                   jTextFieldConta.setText("1");
              }
             else{     
            jTextFieldConta.setText(jTextFieldConta.getText()+"1");
              }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        if ( jTextFieldConta.getText().equals("0")){
                   jTextFieldConta.setText("2");
              }
             else{     
            jTextFieldConta.setText(jTextFieldConta.getText()+"2");
              }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           
        
           if ( jTextFieldConta.getText().equals("0")){
                   jTextFieldConta.setText("4");
              }
             else{     
            jTextFieldConta.setText(jTextFieldConta.getText()+"4");
              }
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            
            if ( jTextFieldConta.getText().equals("0")){
                   jTextFieldConta.setText("5");
              }
             else{     
            jTextFieldConta.setText(jTextFieldConta.getText()+"5");
              }
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
              
          if ( jTextFieldConta.getText().equals("0")){
                   jTextFieldConta.setText("6");
              }
             else{     
            jTextFieldConta.setText(jTextFieldConta.getText()+"6");
              }
      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        if ( jTextFieldConta.getText().equals("0")){
                   jTextFieldConta.setText("7");
              }
             else{     
            jTextFieldConta.setText(jTextFieldConta.getText()+"7");
              }
      
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
             
       if ( jTextFieldConta.getText().equals("0")){
                   jTextFieldConta.setText("8");
              }
             else{     
            jTextFieldConta.setText(jTextFieldConta.getText()+"8");
              }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
             
          if ( jTextFieldConta.getText().equals("0")){
                   jTextFieldConta.setText("9");
              }
             else{     
            jTextFieldConta.setText(jTextFieldConta.getText()+"9");
              }
     
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
               if (jTextFieldConta.getText().equals("0")){
               
                  jTextFieldConta.setText("0");
               }else
           
            jTextFieldConta.setText(jTextFieldConta.getText()+"0");
          
      
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaisActionPerformed
   
       
         operacao =1;
         num1 = Double.parseDouble(jTextFieldConta.getText());
         jTextFieldCalculo.setText(num1 +  "+ ");
          jTextFieldConta.setText("0");
          virgula = 0;
          
         
         
          
        
    }//GEN-LAST:event_jButtonMaisActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
              jTextFieldConta.setText("0");
               virgula = 0;
               jTextFieldCalculo.setText("0");
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaizActionPerformed
         operacao =6;
         num1 = Double.parseDouble(jTextFieldConta.getText());
         jTextFieldCalculo.setText(num1 + "(√)");
        
         jTextFieldConta.setText("0");
         virgula = 0;
         
    }//GEN-LAST:event_jButtonRaizActionPerformed

    private void jTextFieldContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContaActionPerformed

    private void jButtonVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVirgulaActionPerformed
      
        if (virgula == 0){     
         if(jTextFieldConta.getText().equals("0")){
          jTextFieldConta.setText("0.");
          virgula ++;
          
      }else {
            jTextFieldConta.setText(jTextFieldConta.getText()+ ".");
            virgula ++;
            
         
        }
       
         }
         
    }//GEN-LAST:event_jButtonVirgulaActionPerformed

    private void jTextFieldCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCalculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCalculoActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        num2 = Double.parseDouble(jTextFieldConta.getText());
        jTextFieldCalculo.setText(jTextFieldCalculo.getText()+""+num2+" =");
       
        if (operacao == 1){
         jTextFieldConta.setText("" + calc.Soma(num1, num2));
        }
        else if (operacao == 2){
                
        jTextFieldConta.setText(""+ calc.Subtrair(num1, num2));
        }else if (operacao ==3){
        jTextFieldConta.setText(""+ calc.Dividir(num1, num2));
        }else if (operacao ==4){
        jTextFieldConta.setText(""+ calc.Multiplicar(num1, num2));
        }else if (operacao==5){
        jTextFieldConta.setText(""+ calc.Porcentagem(num1, num2));
        }else if (operacao ==6){
          jTextFieldConta.setText(calc.Raiz(num1,num2));
        }
    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void jButtonInversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInversoActionPerformed
       jTextFieldCalculo.setText("1/("+jTextFieldConta.getText()+")=");
       num1 = Double.parseDouble(jTextFieldConta.getText());
       jTextFieldConta.setText(calc.Inverso(num1));
    }//GEN-LAST:event_jButtonInversoActionPerformed

    private void jButtonMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacaoActionPerformed
       operacao = 4;
       num1 = Double.parseDouble(jTextFieldConta.getText());
           jTextFieldCalculo.setText(num1 + "*");
           jTextFieldConta.setText("0");
           virgula = 0;
      
       
    }//GEN-LAST:event_jButtonMultiplicacaoActionPerformed

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
         operacao =2;
         num1 = Double.parseDouble(jTextFieldConta.getText());
         jTextFieldCalculo.setText(num1 + " -");
          jTextFieldConta.setText("0");
          virgula = 0;
        
          if (num1 <0){
          num1 = Double.parseDouble(jTextFieldConta.getText());
          jTextFieldCalculo.setText("-"+ num1);
          jTextFieldConta.setText("0");
          virgula = 0;
          }
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisaoActionPerformed
        operacao =3;
         num1 = Double.parseDouble(jTextFieldConta.getText());
         jTextFieldCalculo.setText(num1 +  " / ");
          jTextFieldConta.setText("0");
          virgula = 0;
    }//GEN-LAST:event_jButtonDivisaoActionPerformed

    private void jButtonPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorcentagemActionPerformed
      operacao =5;
      num1 = Double.parseDouble(jTextFieldConta.getText());
      jTextFieldCalculo.setText(num1 + "%");
      jTextFieldConta.setText("0");
       virgula = 0;
    }//GEN-LAST:event_jButtonPorcentagemActionPerformed
    
    /**j
    ram args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonInverso;
    private javax.swing.JButton jButtonMais;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonMultiplicacao;
    private javax.swing.JButton jButtonPorcentagem;
    private javax.swing.JButton jButtonRaiz;
    private javax.swing.JButton jButtonVirgula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldCalculo;
    private javax.swing.JTextField jTextFieldConta;
    // End of variables declaration//GEN-END:variables
}
